apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-awesome-app
  namespace: production
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: http
    requestPath: /
    port: 8080
